spring.application.name=ms-proyectos
server.port=${SERVER_PORT:8082}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3308/db_proyectos}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root1234}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html