services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin1234

  db_seguridad:
    image: mysql:8.4
    container_name: db_seguridad
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: db_seguridad

  db_proyectos:
    image: mysql:8.4
    container_name: db_proyectos
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: db_proyectos

  db_recursos:
    image: mysql:8.4
    container_name: db_recursos
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: db_recursos

  db_analitica:
    image: mysql:8.4
    container_name: db_analitica
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: db_analitica