spring.application.name=api-gateway
server.port=8080

# Conectar a Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Habilitar descubrimiento automático de rutas
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Rutas manuales hacia los microservicios
spring.cloud.gateway.server.webflux.routes[0].id=ms-seguridad
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ms-seguridad
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/seguridad/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[1].id=ms-proyectos
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ms-proyectos
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/proyectos-api/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[2].id=ms-recursos
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ms-recursos
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/recursos-api/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[3].id=ms-analitica
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ms-analitica
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/analitica/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=1

# CORS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*