spring.application.name=ms-analitica
server.port=${SERVER_PORT:8084}

# Base de datos
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3310/db_analitica}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root1234}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin1234

# URLs de los otros microservicios (para WebClient)
ms.seguridad.url=http://localhost:8081
ms.proyectos.url=http://localhost:8082
ms.recursos.url=http://localhost:8083

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true